# I will utilise the hr.xlsx dataset to predict the salaries(in NGN) to be offered by a HR department to a selection of candidates that applied for a position at Company XYZ with the following performance metrics:
# 3 year experience, 9 test score and 6 interview score
# 2 year experience, 7 test score and 9 interview score
# 15 year experience, 5 test score and 8 interview score
# 1 year experience, 10 test score and 10 test score

Here we go!

In [9]:
! pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5580 sha256=2eafe60c06e75d37157a663bad15cc0732d58c20e399a81944208f2b27673ad7
  Stored in directory: c:\users\emmanuel ogebe\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [10]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [34]:
df = pd.read_excel("hr.xlsx")
df

years_of_experience  aptitude_test_score(out of 10)  \
0                 NaN                               8   
1                 two                               5   
2                 six                               5   
3               seven                               9   
4                four                               2   
5                 one                              10   
6                 NaN                               2   
7               eight                              10   
8                 NaN                              10   
9                 ten                               5   

   interview_score(out of 10)  salary(NGN)  
0                           6        90000  
1                           8       100000  
2                           4       120000  
3                          10       350000  
4                           1        60000  
5                          10       150000  
6                           3        25000  
7                          10       400000  
8                          10       120000  
9                           5       140000

In [35]:
df['years_of_experience'] = df['years_of_experience'].fillna('zero')
df

years_of_experience  aptitude_test_score(out of 10)  \
0                zero                               8   
1                 two                               5   
2                 six                               5   
3               seven                               9   
4                four                               2   
5                 one                              10   
6                zero                               2   
7               eight                              10   
8                zero                              10   
9                 ten                               5   

   interview_score(out of 10)  salary(NGN)  
0                           6        90000  
1                           8       100000  
2                           4       120000  
3                          10       350000  
4                           1        60000  
5                          10       150000  
6                           3        25000  
7                          10       400000  
8                          10       120000  
9                           5       140000

In [36]:
df.years_of_experience = df.years_of_experience.apply(w2n.word_to_num)
df

years_of_experience  aptitude_test_score(out of 10)  \
0                    0                               8   
1                    2                               5   
2                    6                               5   
3                    7                               9   
4                    4                               2   
5                    1                              10   
6                    0                               2   
7                    8                              10   
8                    0                              10   
9                   10                               5   

   interview_score(out of 10)  salary(NGN)  
0                           6        90000  
1                           8       100000  
2                           4       120000  
3                          10       350000  
4                           1        60000  
5                          10       150000  
6                           3        25000  
7                          10       400000  
8                          10       120000  
9                           5       140000

In [37]:
reg = linear_model.LinearRegression()
reg.fit(df[["years_of_experience", "aptitude_test_score(out of 10)",  "interview_score(out of 10)"]], df['salary(NGN)'])

LinearRegression()

In [38]:
reg.predict([[3,9,6]])

array([151573.25574518])

In [39]:
reg.predict([[2,7,9]])

array([160248.75607818])

In [40]:
reg.predict([[15,5,8]])

array([380024.34872496])

In [41]:
reg.predict([[8,10,10]])

array([321865.0624468])

In [44]:
reg.predict([[0,10,10]])

array([165269.80053537])

In [45]:
reg.coef_

array([19574.40773893,  9478.15197575, 15735.40400781])