# I want to predict the homeprices for: a 3 bedroom, 40year old house occupying an area of 3500sqft and a 4 bedroom, 5year old house occupying an area of 2500sqft utilizing the data set


Here we go!

In [25]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [26]:
df = pd.read_excel("homeprices.xlsx")
df

area  bedroom  age   price
0  2600      3.0   10  550000
1  3000      4.0    8  400000
2  3200      NaN   10  380000
3  3600      3.0   15  360000
4  4000      5.0   10  420000
5  4200      NaN   15  390000
6  4600      5.0   20  350000

In [8]:
df.bedroom.median()

4.0

In [10]:
import math
median_bedrooms = math.floor(df.bedroom.median())
median_bedrooms

4

In [12]:
df.bedroom.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    4.0
6    5.0
Name: bedroom, dtype: float64

In [15]:
df.bedroom = df.bedroom.fillna(median_bedrooms)
df

area  bedroom  age   price
0  2600      3.0   10  550000
1  3000      4.0    8  400000
2  3200      4.0   10  380000
3  3600      3.0   15  360000
4  4000      5.0   10  420000
5  4200      4.0   15  390000
6  4600      5.0   20  350000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[["area", "bedroom", "age"]], df.price)

LinearRegression()

In [20]:
reg.coef_

array([ -77.91305358, 9665.14400743, 1666.15051099])

In [21]:
reg.intercept_

628023.3818519665

In [23]:
reg.predict([[3500,3,40]])

array([450969.14679467])

In [24]:
reg.predict([[2500,4,5]])

array([480232.07649427])